services:
  - type: web
    name: cyber-physical-guard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CONFLUENT_BOOTSTRAP_SERVERS
        sync: false
      - key: CONFLUENT_API_KEY
        sync: false
      - key: CONFLUENT_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
